# add colors to reporters
colors: true

# auto exit if test hangs
exit: true

# default reporter
#reporter: spec
reporter: list

# test files
spec:
  - test/mocha.ts
  - test/crc/index.ts
  - test/multibyte/test.ts
  - test/**/*.test.ts
  - test/header.ts

# load ts-node
require:
  - ts-node/register
